export { default as ClassicTemplate } from './ClassicTemplate'
export { default as BUETTemplate } from './BUETTemplate'
export { default as DUTemplate } from './DUTemplate'
export { default as ModernTemplate } from './ModernTemplate'
export { default as KUETTemplate } from './KUETTemplate'
export { default as RUETTemplate } from './RUETTemplate'
export { default as NSUTemplate } from './NSUTemplate'
export { default as ElegantTemplate } from './ElegantTemplate'
